/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillEntry {
  'id' : number,
  'signature' : [] | [string],
  'calculatedTotal' : number,
  'ratePerKm' : number,
  'owner' : Principal,
  'gstNumber' : [] | [string],
  'createdDate' : Time,
  'distanceKm' : number,
  'totalAmount' : number,
  'paymentMode' : PaymentMode,
  'vehicle' : string,
  'partyName' : string,
}
export type DashboardQueryResult = {
    'dashboardError' : { 'message' : string }
  } |
  {
    'dashboardQueryResult' : {
      'expenseTotals' : {
        'totalBank' : number,
        'totalCash' : number,
        'totalUpi' : number,
        'totalExpenses' : number,
        'totalCheque' : number,
        'totalBalancePayment' : number,
      },
      'incomeTotals' : {
        'totalIncome' : number,
        'totalBank' : number,
        'totalCash' : number,
        'totalUpi' : number,
        'totalCheque' : number,
        'totalBalancePayment' : number,
      },
      'dateRange' : { 'endDate' : Time, 'startDate' : Time },
    }
  };
export type ExpenseCategory = { 'salary' : null } |
  { 'cngGas' : null } |
  { 'petrol' : null } |
  { 'commissionVendor' : null } |
  { 'tollCharges' : null } |
  { 'diesel' : null } |
  { 'parkingCharges' : null };
export interface ExpenseEntry {
  'id' : number,
  'paymentDescription' : string,
  'owner' : Principal,
  'date' : Time,
  'description' : string,
  'paymentMode' : PaymentMode,
  'category' : ExpenseCategory,
  'amount' : number,
}
export type ExternalBlob = Uint8Array;
export interface IncomeEntry {
  'assignee' : string,
  'toDestination' : string,
  'paymentDescription' : string,
  'owner' : Principal,
  'fromDestination' : string,
  'date' : Time,
  'description' : string,
  'paymentMode' : PaymentMode,
  'vehicle' : string,
  'bytes' : number,
  'amount' : number,
  'driver' : string,
}
export type PaymentMode = { 'upi' : null } |
  { 'balancePayment' : null } |
  { 'bank' : null } |
  { 'cash' : null } |
  { 'cheque' : null };
export interface PdfReport {
  'id' : number,
  'title' : string,
  'endDate' : [] | [Time],
  'owner' : Principal,
  'period' : ReportPeriod,
  'blob' : ExternalBlob,
  'createdDate' : Time,
  'startDate' : [] | [Time],
}
export type ReportPeriod = { 'financialYear' : bigint } |
  { 'customRange' : { 'endDate' : Time, 'startDate' : Time } } |
  { 'monthly' : { 'month' : bigint, 'year' : bigint } } |
  { 'yearly' : bigint } |
  { 'daily' : { 'day' : bigint, 'month' : bigint, 'year' : bigint } } |
  { 'weekly' : { 'week' : bigint, 'year' : bigint } };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addBillEntry' : ActorMethod<
    [
      string,
      [] | [string],
      string,
      number,
      PaymentMode,
      number,
      number,
      [] | [string],
    ],
    number
  >,
  'addExpenseEntry' : ActorMethod<
    [ExpenseCategory, string, number, Time, PaymentMode, string],
    number
  >,
  'addIncomeEntry' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      number,
      Time,
      PaymentMode,
      string,
    ],
    number
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBillEntry' : ActorMethod<[number], undefined>,
  'deleteExpenseEntry' : ActorMethod<[number], undefined>,
  'deleteIncomeEntry' : ActorMethod<[number], undefined>,
  'deletePdfReport' : ActorMethod<[number], undefined>,
  'getAllPdfReports' : ActorMethod<[], Array<PdfReport>>,
  'getBillById' : ActorMethod<[number], [] | [BillEntry]>,
  'getBillEntries' : ActorMethod<[], Array<BillEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardDataForCustomPeriod' : ActorMethod<
    [Time, Time],
    DashboardQueryResult
  >,
  'getExpenseCategorySummary' : ActorMethod<
    [ExpenseCategory],
    [] | [{ 'total' : number, 'entries' : Array<ExpenseEntry> }]
  >,
  'getExpenseEntries' : ActorMethod<[], Array<ExpenseEntry>>,
  'getExpensePaymentModeTotals' : ActorMethod<
    [],
    {
      'totalBank' : number,
      'totalCash' : number,
      'totalUpi' : number,
      'totalExpenses' : number,
      'totalCheque' : number,
      'totalBalancePayment' : number,
    }
  >,
  'getExpensesByCategory' : ActorMethod<[ExpenseCategory], Array<ExpenseEntry>>,
  'getExpensesByPaymentMode' : ActorMethod<[PaymentMode], Array<ExpenseEntry>>,
  'getExpensesForCustomPeriod' : ActorMethod<[Time, Time], Array<ExpenseEntry>>,
  'getExpensesForFinancialYear' : ActorMethod<[bigint], Array<ExpenseEntry>>,
  'getExpensesForPeriod' : ActorMethod<[Time, Time], Array<ExpenseEntry>>,
  'getFilteredIncomeSummary' : ActorMethod<
    [
      { 'balance' : null } |
        { 'other' : null } |
        { 'bank' : null } |
        { 'cash' : null },
    ],
    [] | [{ 'total' : number, 'entries' : Array<IncomeEntry> }]
  >,
  'getIncomeByPaymentMode' : ActorMethod<[PaymentMode], Array<IncomeEntry>>,
  'getIncomeEntries' : ActorMethod<[], Array<IncomeEntry>>,
  'getIncomeForCustomPeriod' : ActorMethod<[Time, Time], Array<IncomeEntry>>,
  'getIncomeForFinancialYear' : ActorMethod<[bigint], Array<IncomeEntry>>,
  'getIncomeForPeriod' : ActorMethod<[Time, Time], Array<IncomeEntry>>,
  'getIncomePaymentModeTotals' : ActorMethod<
    [],
    {
      'totalIncome' : number,
      'totalBank' : number,
      'totalCash' : number,
      'totalUpi' : number,
      'totalCheque' : number,
      'totalBalancePayment' : number,
    }
  >,
  'getMonthlyReportsForYear' : ActorMethod<[bigint], Array<PdfReport>>,
  'getPdfReport' : ActorMethod<[number], [] | [PdfReport]>,
  'getPdfReportsForCustomPeriod' : ActorMethod<[Time, Time], Array<PdfReport>>,
  'getPdfReportsForFinancialYear' : ActorMethod<[bigint], Array<PdfReport>>,
  'getPdfReportsForPeriod' : ActorMethod<[ReportPeriod], Array<PdfReport>>,
  'getReportsByPeriod' : ActorMethod<[ReportPeriod], Array<PdfReport>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePdfReport' : ActorMethod<
    [string, ReportPeriod, ExternalBlob, [] | [Time], [] | [Time]],
    number
  >,
  'updateBillEntry' : ActorMethod<
    [
      number,
      string,
      [] | [string],
      string,
      number,
      PaymentMode,
      number,
      number,
      [] | [string],
    ],
    undefined
  >,
  'updateExpenseEntry' : ActorMethod<
    [number, ExpenseCategory, string, number, Time, PaymentMode, string],
    undefined
  >,
  'updateIncomeEntry' : ActorMethod<
    [
      number,
      string,
      string,
      string,
      string,
      string,
      string,
      number,
      Time,
      PaymentMode,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];