/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentMode = IDL.Variant({
  'upi' : IDL.Null,
  'balancePayment' : IDL.Null,
  'bank' : IDL.Null,
  'cash' : IDL.Null,
  'cheque' : IDL.Null,
});
export const ExpenseCategory = IDL.Variant({
  'salary' : IDL.Null,
  'cngGas' : IDL.Null,
  'petrol' : IDL.Null,
  'commissionVendor' : IDL.Null,
  'tollCharges' : IDL.Null,
  'diesel' : IDL.Null,
  'parkingCharges' : IDL.Null,
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReportPeriod = IDL.Variant({
  'financialYear' : IDL.Nat,
  'customRange' : IDL.Record({ 'endDate' : Time, 'startDate' : Time }),
  'monthly' : IDL.Record({ 'month' : IDL.Nat, 'year' : IDL.Nat }),
  'yearly' : IDL.Nat,
  'daily' : IDL.Record({
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  }),
  'weekly' : IDL.Record({ 'week' : IDL.Nat, 'year' : IDL.Nat }),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PdfReport = IDL.Record({
  'id' : IDL.Nat32,
  'title' : IDL.Text,
  'endDate' : IDL.Opt(Time),
  'owner' : IDL.Principal,
  'period' : ReportPeriod,
  'blob' : ExternalBlob,
  'createdDate' : Time,
  'startDate' : IDL.Opt(Time),
});
export const BillEntry = IDL.Record({
  'id' : IDL.Nat32,
  'signature' : IDL.Opt(IDL.Text),
  'calculatedTotal' : IDL.Float64,
  'ratePerKm' : IDL.Float64,
  'owner' : IDL.Principal,
  'gstNumber' : IDL.Opt(IDL.Text),
  'createdDate' : Time,
  'distanceKm' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'paymentMode' : PaymentMode,
  'vehicle' : IDL.Text,
  'partyName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardQueryResult = IDL.Variant({
  'dashboardError' : IDL.Record({ 'message' : IDL.Text }),
  'dashboardQueryResult' : IDL.Record({
    'expenseTotals' : IDL.Record({
      'totalBank' : IDL.Float64,
      'totalCash' : IDL.Float64,
      'totalUpi' : IDL.Float64,
      'totalExpenses' : IDL.Float64,
      'totalCheque' : IDL.Float64,
      'totalBalancePayment' : IDL.Float64,
    }),
    'incomeTotals' : IDL.Record({
      'totalIncome' : IDL.Float64,
      'totalBank' : IDL.Float64,
      'totalCash' : IDL.Float64,
      'totalUpi' : IDL.Float64,
      'totalCheque' : IDL.Float64,
      'totalBalancePayment' : IDL.Float64,
    }),
    'dateRange' : IDL.Record({ 'endDate' : Time, 'startDate' : Time }),
  }),
});
export const ExpenseEntry = IDL.Record({
  'id' : IDL.Nat32,
  'paymentDescription' : IDL.Text,
  'owner' : IDL.Principal,
  'date' : Time,
  'description' : IDL.Text,
  'paymentMode' : PaymentMode,
  'category' : ExpenseCategory,
  'amount' : IDL.Float64,
});
export const IncomeEntry = IDL.Record({
  'assignee' : IDL.Text,
  'toDestination' : IDL.Text,
  'paymentDescription' : IDL.Text,
  'owner' : IDL.Principal,
  'fromDestination' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'paymentMode' : PaymentMode,
  'vehicle' : IDL.Text,
  'bytes' : IDL.Nat32,
  'amount' : IDL.Float64,
  'driver' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBillEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Float64,
        PaymentMode,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat32],
      [],
    ),
  'addExpenseEntry' : IDL.Func(
      [ExpenseCategory, IDL.Text, IDL.Float64, Time, PaymentMode, IDL.Text],
      [IDL.Nat32],
      [],
    ),
  'addIncomeEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        Time,
        PaymentMode,
        IDL.Text,
      ],
      [IDL.Nat32],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBillEntry' : IDL.Func([IDL.Nat32], [], []),
  'deleteExpenseEntry' : IDL.Func([IDL.Nat32], [], []),
  'deleteIncomeEntry' : IDL.Func([IDL.Nat32], [], []),
  'deletePdfReport' : IDL.Func([IDL.Nat32], [], []),
  'getAllPdfReports' : IDL.Func([], [IDL.Vec(PdfReport)], ['query']),
  'getBillById' : IDL.Func([IDL.Nat32], [IDL.Opt(BillEntry)], ['query']),
  'getBillEntries' : IDL.Func([], [IDL.Vec(BillEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardDataForCustomPeriod' : IDL.Func(
      [Time, Time],
      [DashboardQueryResult],
      ['query'],
    ),
  'getExpenseCategorySummary' : IDL.Func(
      [ExpenseCategory],
      [
        IDL.Opt(
          IDL.Record({
            'total' : IDL.Float64,
            'entries' : IDL.Vec(ExpenseEntry),
          })
        ),
      ],
      ['query'],
    ),
  'getExpenseEntries' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
  'getExpensePaymentModeTotals' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalBank' : IDL.Float64,
          'totalCash' : IDL.Float64,
          'totalUpi' : IDL.Float64,
          'totalExpenses' : IDL.Float64,
          'totalCheque' : IDL.Float64,
          'totalBalancePayment' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getExpensesByCategory' : IDL.Func(
      [ExpenseCategory],
      [IDL.Vec(ExpenseEntry)],
      ['query'],
    ),
  'getExpensesByPaymentMode' : IDL.Func(
      [PaymentMode],
      [IDL.Vec(ExpenseEntry)],
      ['query'],
    ),
  'getExpensesForCustomPeriod' : IDL.Func(
      [Time, Time],
      [IDL.Vec(ExpenseEntry)],
      ['query'],
    ),
  'getExpensesForFinancialYear' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ExpenseEntry)],
      ['query'],
    ),
  'getExpensesForPeriod' : IDL.Func(
      [Time, Time],
      [IDL.Vec(ExpenseEntry)],
      ['query'],
    ),
  'getFilteredIncomeSummary' : IDL.Func(
      [
        IDL.Variant({
          'balance' : IDL.Null,
          'other' : IDL.Null,
          'bank' : IDL.Null,
          'cash' : IDL.Null,
        }),
      ],
      [
        IDL.Opt(
          IDL.Record({
            'total' : IDL.Float64,
            'entries' : IDL.Vec(IncomeEntry),
          })
        ),
      ],
      ['query'],
    ),
  'getIncomeByPaymentMode' : IDL.Func(
      [PaymentMode],
      [IDL.Vec(IncomeEntry)],
      ['query'],
    ),
  'getIncomeEntries' : IDL.Func([], [IDL.Vec(IncomeEntry)], ['query']),
  'getIncomeForCustomPeriod' : IDL.Func(
      [Time, Time],
      [IDL.Vec(IncomeEntry)],
      ['query'],
    ),
  'getIncomeForFinancialYear' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IncomeEntry)],
      ['query'],
    ),
  'getIncomeForPeriod' : IDL.Func(
      [Time, Time],
      [IDL.Vec(IncomeEntry)],
      ['query'],
    ),
  'getIncomePaymentModeTotals' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalIncome' : IDL.Float64,
          'totalBank' : IDL.Float64,
          'totalCash' : IDL.Float64,
          'totalUpi' : IDL.Float64,
          'totalCheque' : IDL.Float64,
          'totalBalancePayment' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getMonthlyReportsForYear' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PdfReport)],
      ['query'],
    ),
  'getPdfReport' : IDL.Func([IDL.Nat32], [IDL.Opt(PdfReport)], ['query']),
  'getPdfReportsForCustomPeriod' : IDL.Func(
      [Time, Time],
      [IDL.Vec(PdfReport)],
      ['query'],
    ),
  'getPdfReportsForFinancialYear' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PdfReport)],
      ['query'],
    ),
  'getPdfReportsForPeriod' : IDL.Func(
      [ReportPeriod],
      [IDL.Vec(PdfReport)],
      ['query'],
    ),
  'getReportsByPeriod' : IDL.Func(
      [ReportPeriod],
      [IDL.Vec(PdfReport)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePdfReport' : IDL.Func(
      [IDL.Text, ReportPeriod, ExternalBlob, IDL.Opt(Time), IDL.Opt(Time)],
      [IDL.Nat32],
      [],
    ),
  'updateBillEntry' : IDL.Func(
      [
        IDL.Nat32,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Float64,
        PaymentMode,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateExpenseEntry' : IDL.Func(
      [
        IDL.Nat32,
        ExpenseCategory,
        IDL.Text,
        IDL.Float64,
        Time,
        PaymentMode,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateIncomeEntry' : IDL.Func(
      [
        IDL.Nat32,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        Time,
        PaymentMode,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentMode = IDL.Variant({
    'upi' : IDL.Null,
    'balancePayment' : IDL.Null,
    'bank' : IDL.Null,
    'cash' : IDL.Null,
    'cheque' : IDL.Null,
  });
  const ExpenseCategory = IDL.Variant({
    'salary' : IDL.Null,
    'cngGas' : IDL.Null,
    'petrol' : IDL.Null,
    'commissionVendor' : IDL.Null,
    'tollCharges' : IDL.Null,
    'diesel' : IDL.Null,
    'parkingCharges' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReportPeriod = IDL.Variant({
    'financialYear' : IDL.Nat,
    'customRange' : IDL.Record({ 'endDate' : Time, 'startDate' : Time }),
    'monthly' : IDL.Record({ 'month' : IDL.Nat, 'year' : IDL.Nat }),
    'yearly' : IDL.Nat,
    'daily' : IDL.Record({
      'day' : IDL.Nat,
      'month' : IDL.Nat,
      'year' : IDL.Nat,
    }),
    'weekly' : IDL.Record({ 'week' : IDL.Nat, 'year' : IDL.Nat }),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PdfReport = IDL.Record({
    'id' : IDL.Nat32,
    'title' : IDL.Text,
    'endDate' : IDL.Opt(Time),
    'owner' : IDL.Principal,
    'period' : ReportPeriod,
    'blob' : ExternalBlob,
    'createdDate' : Time,
    'startDate' : IDL.Opt(Time),
  });
  const BillEntry = IDL.Record({
    'id' : IDL.Nat32,
    'signature' : IDL.Opt(IDL.Text),
    'calculatedTotal' : IDL.Float64,
    'ratePerKm' : IDL.Float64,
    'owner' : IDL.Principal,
    'gstNumber' : IDL.Opt(IDL.Text),
    'createdDate' : Time,
    'distanceKm' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'paymentMode' : PaymentMode,
    'vehicle' : IDL.Text,
    'partyName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardQueryResult = IDL.Variant({
    'dashboardError' : IDL.Record({ 'message' : IDL.Text }),
    'dashboardQueryResult' : IDL.Record({
      'expenseTotals' : IDL.Record({
        'totalBank' : IDL.Float64,
        'totalCash' : IDL.Float64,
        'totalUpi' : IDL.Float64,
        'totalExpenses' : IDL.Float64,
        'totalCheque' : IDL.Float64,
        'totalBalancePayment' : IDL.Float64,
      }),
      'incomeTotals' : IDL.Record({
        'totalIncome' : IDL.Float64,
        'totalBank' : IDL.Float64,
        'totalCash' : IDL.Float64,
        'totalUpi' : IDL.Float64,
        'totalCheque' : IDL.Float64,
        'totalBalancePayment' : IDL.Float64,
      }),
      'dateRange' : IDL.Record({ 'endDate' : Time, 'startDate' : Time }),
    }),
  });
  const ExpenseEntry = IDL.Record({
    'id' : IDL.Nat32,
    'paymentDescription' : IDL.Text,
    'owner' : IDL.Principal,
    'date' : Time,
    'description' : IDL.Text,
    'paymentMode' : PaymentMode,
    'category' : ExpenseCategory,
    'amount' : IDL.Float64,
  });
  const IncomeEntry = IDL.Record({
    'assignee' : IDL.Text,
    'toDestination' : IDL.Text,
    'paymentDescription' : IDL.Text,
    'owner' : IDL.Principal,
    'fromDestination' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'paymentMode' : PaymentMode,
    'vehicle' : IDL.Text,
    'bytes' : IDL.Nat32,
    'amount' : IDL.Float64,
    'driver' : IDL.Text,
  });
  
  return IDL.Service({
    'addBillEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Float64,
          PaymentMode,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat32],
        [],
      ),
    'addExpenseEntry' : IDL.Func(
        [ExpenseCategory, IDL.Text, IDL.Float64, Time, PaymentMode, IDL.Text],
        [IDL.Nat32],
        [],
      ),
    'addIncomeEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          Time,
          PaymentMode,
          IDL.Text,
        ],
        [IDL.Nat32],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBillEntry' : IDL.Func([IDL.Nat32], [], []),
    'deleteExpenseEntry' : IDL.Func([IDL.Nat32], [], []),
    'deleteIncomeEntry' : IDL.Func([IDL.Nat32], [], []),
    'deletePdfReport' : IDL.Func([IDL.Nat32], [], []),
    'getAllPdfReports' : IDL.Func([], [IDL.Vec(PdfReport)], ['query']),
    'getBillById' : IDL.Func([IDL.Nat32], [IDL.Opt(BillEntry)], ['query']),
    'getBillEntries' : IDL.Func([], [IDL.Vec(BillEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardDataForCustomPeriod' : IDL.Func(
        [Time, Time],
        [DashboardQueryResult],
        ['query'],
      ),
    'getExpenseCategorySummary' : IDL.Func(
        [ExpenseCategory],
        [
          IDL.Opt(
            IDL.Record({
              'total' : IDL.Float64,
              'entries' : IDL.Vec(ExpenseEntry),
            })
          ),
        ],
        ['query'],
      ),
    'getExpenseEntries' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
    'getExpensePaymentModeTotals' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalBank' : IDL.Float64,
            'totalCash' : IDL.Float64,
            'totalUpi' : IDL.Float64,
            'totalExpenses' : IDL.Float64,
            'totalCheque' : IDL.Float64,
            'totalBalancePayment' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getExpensesByCategory' : IDL.Func(
        [ExpenseCategory],
        [IDL.Vec(ExpenseEntry)],
        ['query'],
      ),
    'getExpensesByPaymentMode' : IDL.Func(
        [PaymentMode],
        [IDL.Vec(ExpenseEntry)],
        ['query'],
      ),
    'getExpensesForCustomPeriod' : IDL.Func(
        [Time, Time],
        [IDL.Vec(ExpenseEntry)],
        ['query'],
      ),
    'getExpensesForFinancialYear' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ExpenseEntry)],
        ['query'],
      ),
    'getExpensesForPeriod' : IDL.Func(
        [Time, Time],
        [IDL.Vec(ExpenseEntry)],
        ['query'],
      ),
    'getFilteredIncomeSummary' : IDL.Func(
        [
          IDL.Variant({
            'balance' : IDL.Null,
            'other' : IDL.Null,
            'bank' : IDL.Null,
            'cash' : IDL.Null,
          }),
        ],
        [
          IDL.Opt(
            IDL.Record({
              'total' : IDL.Float64,
              'entries' : IDL.Vec(IncomeEntry),
            })
          ),
        ],
        ['query'],
      ),
    'getIncomeByPaymentMode' : IDL.Func(
        [PaymentMode],
        [IDL.Vec(IncomeEntry)],
        ['query'],
      ),
    'getIncomeEntries' : IDL.Func([], [IDL.Vec(IncomeEntry)], ['query']),
    'getIncomeForCustomPeriod' : IDL.Func(
        [Time, Time],
        [IDL.Vec(IncomeEntry)],
        ['query'],
      ),
    'getIncomeForFinancialYear' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IncomeEntry)],
        ['query'],
      ),
    'getIncomeForPeriod' : IDL.Func(
        [Time, Time],
        [IDL.Vec(IncomeEntry)],
        ['query'],
      ),
    'getIncomePaymentModeTotals' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalIncome' : IDL.Float64,
            'totalBank' : IDL.Float64,
            'totalCash' : IDL.Float64,
            'totalUpi' : IDL.Float64,
            'totalCheque' : IDL.Float64,
            'totalBalancePayment' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getMonthlyReportsForYear' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PdfReport)],
        ['query'],
      ),
    'getPdfReport' : IDL.Func([IDL.Nat32], [IDL.Opt(PdfReport)], ['query']),
    'getPdfReportsForCustomPeriod' : IDL.Func(
        [Time, Time],
        [IDL.Vec(PdfReport)],
        ['query'],
      ),
    'getPdfReportsForFinancialYear' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PdfReport)],
        ['query'],
      ),
    'getPdfReportsForPeriod' : IDL.Func(
        [ReportPeriod],
        [IDL.Vec(PdfReport)],
        ['query'],
      ),
    'getReportsByPeriod' : IDL.Func(
        [ReportPeriod],
        [IDL.Vec(PdfReport)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePdfReport' : IDL.Func(
        [IDL.Text, ReportPeriod, ExternalBlob, IDL.Opt(Time), IDL.Opt(Time)],
        [IDL.Nat32],
        [],
      ),
    'updateBillEntry' : IDL.Func(
        [
          IDL.Nat32,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Float64,
          PaymentMode,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateExpenseEntry' : IDL.Func(
        [
          IDL.Nat32,
          ExpenseCategory,
          IDL.Text,
          IDL.Float64,
          Time,
          PaymentMode,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateIncomeEntry' : IDL.Func(
        [
          IDL.Nat32,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          Time,
          PaymentMode,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };