/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type ReportPeriod = {
    __kind__: "financialYear";
    financialYear: bigint;
} | {
    __kind__: "customRange";
    customRange: {
        endDate: Time;
        startDate: Time;
    };
} | {
    __kind__: "monthly";
    monthly: {
        month: bigint;
        year: bigint;
    };
} | {
    __kind__: "yearly";
    yearly: bigint;
} | {
    __kind__: "daily";
    daily: {
        day: bigint;
        month: bigint;
        year: bigint;
    };
} | {
    __kind__: "weekly";
    weekly: {
        week: bigint;
        year: bigint;
    };
};
export interface BillEntry {
    id: number;
    signature?: string;
    calculatedTotal: number;
    ratePerKm: number;
    owner: Principal;
    gstNumber?: string;
    createdDate: Time;
    distanceKm: number;
    totalAmount: number;
    paymentMode: PaymentMode;
    vehicle: string;
    partyName: string;
}
export type DashboardQueryResult = {
    __kind__: "dashboardError";
    dashboardError: {
        message: string;
    };
} | {
    __kind__: "dashboardQueryResult";
    dashboardQueryResult: {
        expenseTotals: {
            totalBank: number;
            totalCash: number;
            totalUpi: number;
            totalExpenses: number;
            totalCheque: number;
            totalBalancePayment: number;
        };
        incomeTotals: {
            totalIncome: number;
            totalBank: number;
            totalCash: number;
            totalUpi: number;
            totalCheque: number;
            totalBalancePayment: number;
        };
        dateRange: {
            endDate: Time;
            startDate: Time;
        };
    };
};
export interface ExpenseEntry {
    id: number;
    paymentDescription: string;
    owner: Principal;
    date: Time;
    description: string;
    paymentMode: PaymentMode;
    category: ExpenseCategory;
    amount: number;
}
export interface IncomeEntry {
    assignee: string;
    toDestination: string;
    paymentDescription: string;
    owner: Principal;
    fromDestination: string;
    date: Time;
    description: string;
    paymentMode: PaymentMode;
    vehicle: string;
    bytes: number;
    amount: number;
    driver: string;
}
export interface UserProfile {
    name: string;
}
export interface PdfReport {
    id: number;
    title: string;
    endDate?: Time;
    owner: Principal;
    period: ReportPeriod;
    blob: ExternalBlob;
    createdDate: Time;
    startDate?: Time;
}
export enum ExpenseCategory {
    salary = "salary",
    cngGas = "cngGas",
    petrol = "petrol",
    commissionVendor = "commissionVendor",
    tollCharges = "tollCharges",
    diesel = "diesel",
    parkingCharges = "parkingCharges",
    fraud = "fraud",
    maintenanceAndRepair = "maintenanceAndRepair",
    otherExpenses = "otherExpenses",
    purchase = "purchase"
}
export enum PaymentMode {
    upi = "upi",
    balancePayment = "balancePayment",
    bank = "bank",
    cash = "cash",
    cheque = "cheque"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_balance_other_bank_cash {
    balance = "balance",
    other = "other",
    bank = "bank",
    cash = "cash"
}
export interface backendInterface {
    addBillEntry(partyName: string, gstNumber: string | null, vehicle: string, totalAmount: number, paymentMode: PaymentMode, distanceKm: number, ratePerKm: number, signature: string | null): Promise<number>;
    addExpenseEntry(category: ExpenseCategory, description: string, amount: number, date: Time, paymentMode: PaymentMode, paymentDescription: string): Promise<number>;
    addIncomeEntry(description: string, fromDestination: string, toDestination: string, assignee: string, driver: string, vehicle: string, amount: number, date: Time, paymentMode: PaymentMode, paymentDescription: string): Promise<number>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBillEntry(id: number): Promise<void>;
    deleteExpenseEntry(id: number): Promise<void>;
    deleteIncomeEntry(id: number): Promise<void>;
    deletePdfReport(id: number): Promise<void>;
    getAllPdfReports(): Promise<Array<PdfReport>>;
    getBillById(id: number): Promise<BillEntry | null>;
    getBillEntries(): Promise<Array<BillEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardDataForCustomPeriod(startDate: Time, endDate: Time): Promise<DashboardQueryResult>;
    getExpenseCategorySummary(category: ExpenseCategory): Promise<{
        total: number;
        entries: Array<ExpenseEntry>;
    } | null>;
    getExpenseEntries(): Promise<Array<ExpenseEntry>>;
    getExpensePaymentModeTotals(): Promise<{
        totalBank: number;
        totalCash: number;
        totalUpi: number;
        totalExpenses: number;
        totalCheque: number;
        totalBalancePayment: number;
    }>;
    getExpensesByCategory(category: ExpenseCategory): Promise<Array<ExpenseEntry>>;
    getExpensesByPaymentMode(paymentMode: PaymentMode): Promise<Array<ExpenseEntry>>;
    getExpensesForCustomPeriod(startDate: Time, endDate: Time): Promise<Array<ExpenseEntry>>;
    getExpensesForFinancialYear(year: bigint): Promise<Array<ExpenseEntry>>;
    getExpensesForPeriod(startDate: Time, endDate: Time): Promise<Array<ExpenseEntry>>;
    getFilteredIncomeSummary(filter: Variant_balance_other_bank_cash): Promise<{
        total: number;
        entries: Array<IncomeEntry>;
    } | null>;
    getIncomeByPaymentMode(paymentMode: PaymentMode): Promise<Array<IncomeEntry>>;
    getIncomeEntries(): Promise<Array<IncomeEntry>>;
    getIncomeForCustomPeriod(startDate: Time, endDate: Time): Promise<Array<IncomeEntry>>;
    getIncomeForFinancialYear(year: bigint): Promise<Array<IncomeEntry>>;
    getIncomeForPeriod(startDate: Time, endDate: Time): Promise<Array<IncomeEntry>>;
    getIncomePaymentModeTotals(): Promise<{
        totalIncome: number;
        totalBank: number;
        totalCash: number;
        totalUpi: number;
        totalCheque: number;
        totalBalancePayment: number;
    }>;
    getMonthlyReportsForYear(year: bigint): Promise<Array<PdfReport>>;
    getPdfReport(id: number): Promise<PdfReport | null>;
    getPdfReportsForCustomPeriod(startDate: Time, endDate: Time): Promise<Array<PdfReport>>;
    getPdfReportsForFinancialYear(year: bigint): Promise<Array<PdfReport>>;
    getPdfReportsForPeriod(period: ReportPeriod): Promise<Array<PdfReport>>;
    getReportsByPeriod(period: ReportPeriod): Promise<Array<PdfReport>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePdfReport(title: string, period: ReportPeriod, blob: ExternalBlob, startDate: Time | null, endDate: Time | null): Promise<number>;
    updateBillEntry(id: number, partyName: string, gstNumber: string | null, vehicle: string, totalAmount: number, paymentMode: PaymentMode, distanceKm: number, ratePerKm: number, signature: string | null): Promise<void>;
    updateExpenseEntry(id: number, category: ExpenseCategory, description: string, amount: number, date: Time, paymentMode: PaymentMode, paymentDescription: string): Promise<void>;
    updateIncomeEntry(id: number, description: string, fromDestination: string, toDestination: string, assignee: string, driver: string, vehicle: string, amount: number, date: Time, paymentMode: PaymentMode, paymentDescription: string): Promise<void>;
}
import type { BillEntry as _BillEntry, DashboardQueryResult as _DashboardQueryResult, ExpenseCategory as _ExpenseCategory, ExpenseEntry as _ExpenseEntry, ExternalBlob as _ExternalBlob, IncomeEntry as _IncomeEntry, PaymentMode as _PaymentMode, PdfReport as _PdfReport, ReportPeriod as _ReportPeriod, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBillEntry(arg0: string, arg1: string | null, arg2: string, arg3: number, arg4: PaymentMode, arg5: number, arg6: number, arg7: string | null): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.addBillEntry(arg0, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg1), arg2, arg3, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg4), arg5, arg6, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBillEntry(arg0, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg1), arg2, arg3, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg4), arg5, arg6, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg7));
            return result;
        }
    }
    async addExpenseEntry(arg0: ExpenseCategory, arg1: string, arg2: number, arg3: Time, arg4: PaymentMode, arg5: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpenseEntry(to_candid_ExpenseCategory_n4(this.uploadFile, this.downloadFile, arg0), arg1, arg2, arg3, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpenseEntry(to_candid_ExpenseCategory_n4(this.uploadFile, this.downloadFile, arg0), arg1, arg2, arg3, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg4), arg5);
            return result;
        }
    }
    async addIncomeEntry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: number, arg7: Time, arg8: PaymentMode, arg9: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncomeEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg8), arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncomeEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg8), arg9);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async deleteBillEntry(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBillEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBillEntry(arg0);
            return result;
        }
    }
    async deleteExpenseEntry(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpenseEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpenseEntry(arg0);
            return result;
        }
    }
    async deleteIncomeEntry(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIncomeEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIncomeEntry(arg0);
            return result;
        }
    }
    async deletePdfReport(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePdfReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePdfReport(arg0);
            return result;
        }
    }
    async getAllPdfReports(): Promise<Array<PdfReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPdfReports();
                return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPdfReports();
            return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBillById(arg0: number): Promise<BillEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillById(arg0);
                return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillById(arg0);
            return from_candid_opt_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBillEntries(): Promise<Array<BillEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillEntries();
                return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillEntries();
            return from_candid_vec_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDashboardDataForCustomPeriod(arg0: Time, arg1: Time): Promise<DashboardQueryResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardDataForCustomPeriod(arg0, arg1);
                return from_candid_DashboardQueryResult_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardDataForCustomPeriod(arg0, arg1);
            return from_candid_DashboardQueryResult_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getExpenseCategorySummary(arg0: ExpenseCategory): Promise<{
        total: number;
        entries: Array<ExpenseEntry>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseCategorySummary(to_candid_ExpenseCategory_n4(this.uploadFile, this.downloadFile, arg0));
                return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseCategorySummary(to_candid_ExpenseCategory_n4(this.uploadFile, this.downloadFile, arg0));
            return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getExpenseEntries(): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseEntries();
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseEntries();
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getExpensePaymentModeTotals(): Promise<{
        totalBank: number;
        totalCash: number;
        totalUpi: number;
        totalExpenses: number;
        totalCheque: number;
        totalBalancePayment: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensePaymentModeTotals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensePaymentModeTotals();
            return result;
        }
    }
    async getExpensesByCategory(arg0: ExpenseCategory): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByCategory(to_candid_ExpenseCategory_n4(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByCategory(to_candid_ExpenseCategory_n4(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getExpensesByPaymentMode(arg0: PaymentMode): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByPaymentMode(to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByPaymentMode(to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getExpensesForCustomPeriod(arg0: Time, arg1: Time): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesForCustomPeriod(arg0, arg1);
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesForCustomPeriod(arg0, arg1);
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getExpensesForFinancialYear(arg0: bigint): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesForFinancialYear(arg0);
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesForFinancialYear(arg0);
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getExpensesForPeriod(arg0: Time, arg1: Time): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesForPeriod(arg0, arg1);
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesForPeriod(arg0, arg1);
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFilteredIncomeSummary(arg0: Variant_balance_other_bank_cash): Promise<{
        total: number;
        entries: Array<IncomeEntry>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredIncomeSummary(to_candid_variant_n34(this.uploadFile, this.downloadFile, arg0));
                return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredIncomeSummary(to_candid_variant_n34(this.uploadFile, this.downloadFile, arg0));
            return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
        }
    }
    async getIncomeByPaymentMode(arg0: PaymentMode): Promise<Array<IncomeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeByPaymentMode(to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeByPaymentMode(to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async getIncomeEntries(): Promise<Array<IncomeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeEntries();
                return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeEntries();
            return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async getIncomeForCustomPeriod(arg0: Time, arg1: Time): Promise<Array<IncomeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeForCustomPeriod(arg0, arg1);
                return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeForCustomPeriod(arg0, arg1);
            return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async getIncomeForFinancialYear(arg0: bigint): Promise<Array<IncomeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeForFinancialYear(arg0);
                return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeForFinancialYear(arg0);
            return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async getIncomeForPeriod(arg0: Time, arg1: Time): Promise<Array<IncomeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomeForPeriod(arg0, arg1);
                return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomeForPeriod(arg0, arg1);
            return from_candid_vec_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async getIncomePaymentModeTotals(): Promise<{
        totalIncome: number;
        totalBank: number;
        totalCash: number;
        totalUpi: number;
        totalCheque: number;
        totalBalancePayment: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomePaymentModeTotals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomePaymentModeTotals();
            return result;
        }
    }
    async getMonthlyReportsForYear(arg0: bigint): Promise<Array<PdfReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyReportsForYear(arg0);
                return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyReportsForYear(arg0);
            return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPdfReport(arg0: number): Promise<PdfReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdfReport(arg0);
                return from_candid_opt_n40(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdfReport(arg0);
            return from_candid_opt_n40(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPdfReportsForCustomPeriod(arg0: Time, arg1: Time): Promise<Array<PdfReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdfReportsForCustomPeriod(arg0, arg1);
                return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdfReportsForCustomPeriod(arg0, arg1);
            return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPdfReportsForFinancialYear(arg0: bigint): Promise<Array<PdfReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdfReportsForFinancialYear(arg0);
                return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdfReportsForFinancialYear(arg0);
            return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPdfReportsForPeriod(arg0: ReportPeriod): Promise<Array<PdfReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdfReportsForPeriod(to_candid_ReportPeriod_n41(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdfReportsForPeriod(to_candid_ReportPeriod_n41(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getReportsByPeriod(arg0: ReportPeriod): Promise<Array<PdfReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByPeriod(to_candid_ReportPeriod_n41(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByPeriod(to_candid_ReportPeriod_n41(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async savePdfReport(arg0: string, arg1: ReportPeriod, arg2: ExternalBlob, arg3: Time | null, arg4: Time | null): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.savePdfReport(arg0, to_candid_ReportPeriod_n41(this.uploadFile, this.downloadFile, arg1), await to_candid_ExternalBlob_n43(this.uploadFile, this.downloadFile, arg2), to_candid_opt_n44(this.uploadFile, this.downloadFile, arg3), to_candid_opt_n44(this.uploadFile, this.downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePdfReport(arg0, to_candid_ReportPeriod_n41(this.uploadFile, this.downloadFile, arg1), await to_candid_ExternalBlob_n43(this.uploadFile, this.downloadFile, arg2), to_candid_opt_n44(this.uploadFile, this.downloadFile, arg3), to_candid_opt_n44(this.uploadFile, this.downloadFile, arg4));
            return result;
        }
    }
    async updateBillEntry(arg0: number, arg1: string, arg2: string | null, arg3: string, arg4: number, arg5: PaymentMode, arg6: number, arg7: number, arg8: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBillEntry(arg0, arg1, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg2), arg3, arg4, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg5), arg6, arg7, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBillEntry(arg0, arg1, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg2), arg3, arg4, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg5), arg6, arg7, to_candid_opt_n1(this.uploadFile, this.downloadFile, arg8));
            return result;
        }
    }
    async updateExpenseEntry(arg0: number, arg1: ExpenseCategory, arg2: string, arg3: number, arg4: Time, arg5: PaymentMode, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpenseEntry(arg0, to_candid_ExpenseCategory_n4(this.uploadFile, this.downloadFile, arg1), arg2, arg3, arg4, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpenseEntry(arg0, to_candid_ExpenseCategory_n4(this.uploadFile, this.downloadFile, arg1), arg2, arg3, arg4, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg5), arg6);
            return result;
        }
    }
    async updateIncomeEntry(arg0: number, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: number, arg8: Time, arg9: PaymentMode, arg10: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncomeEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg9), arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncomeEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_PaymentMode_n2(this.uploadFile, this.downloadFile, arg9), arg10);
            return result;
        }
    }
}
function from_candid_BillEntry_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillEntry): BillEntry {
    return from_candid_record_n17(uploadFile, downloadFile, value);
}
function from_candid_DashboardQueryResult_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardQueryResult): DashboardQueryResult {
    return from_candid_variant_n26(uploadFile, downloadFile, value);
}
function from_candid_ExpenseCategory_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseCategory): ExpenseCategory {
    return from_candid_variant_n33(uploadFile, downloadFile, value);
}
function from_candid_ExpenseEntry_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseEntry): ExpenseEntry {
    return from_candid_record_n31(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
function from_candid_IncomeEntry_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncomeEntry): IncomeEntry {
    return from_candid_record_n39(uploadFile, downloadFile, value);
}
function from_candid_PaymentMode_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n20(uploadFile, downloadFile, value);
}
async function from_candid_PdfReport_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PdfReport): Promise<PdfReport> {
    return await from_candid_record_n10(uploadFile, downloadFile, value);
}
function from_candid_ReportPeriod_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportPeriod): ReportPeriod {
    return from_candid_variant_n13(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(uploadFile, downloadFile, value);
}
function from_candid_opt_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BillEntry]): BillEntry | null {
    return value.length === 0 ? null : from_candid_BillEntry_n16(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        total: number;
        entries: Array<_ExpenseEntry>;
    }]): {
    total: number;
    entries: Array<ExpenseEntry>;
} | null {
    return value.length === 0 ? null : from_candid_record_n28(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        total: number;
        entries: Array<_IncomeEntry>;
    }]): {
    total: number;
    entries: Array<IncomeEntry>;
} | null {
    return value.length === 0 ? null : from_candid_record_n36(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PdfReport]): Promise<PdfReport | null> {
    return value.length === 0 ? null : await from_candid_PdfReport_n9(uploadFile, downloadFile, value[0]);
}
async function from_candid_record_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    title: string;
    endDate: [] | [_Time];
    owner: Principal;
    period: _ReportPeriod;
    blob: _ExternalBlob;
    createdDate: _Time;
    startDate: [] | [_Time];
}): Promise<{
    id: number;
    title: string;
    endDate?: Time;
    owner: Principal;
    period: ReportPeriod;
    blob: ExternalBlob;
    createdDate: Time;
    startDate?: Time;
}> {
    return {
        id: value.id,
        title: value.title,
        endDate: record_opt_to_undefined(from_candid_opt_n11(uploadFile, downloadFile, value.endDate)),
        owner: value.owner,
        period: from_candid_ReportPeriod_n12(uploadFile, downloadFile, value.period),
        blob: await from_candid_ExternalBlob_n14(uploadFile, downloadFile, value.blob),
        createdDate: value.createdDate,
        startDate: record_opt_to_undefined(from_candid_opt_n11(uploadFile, downloadFile, value.startDate))
    };
}
function from_candid_record_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    signature: [] | [string];
    calculatedTotal: number;
    ratePerKm: number;
    owner: Principal;
    gstNumber: [] | [string];
    createdDate: _Time;
    distanceKm: number;
    totalAmount: number;
    paymentMode: _PaymentMode;
    vehicle: string;
    partyName: string;
}): {
    id: number;
    signature?: string;
    calculatedTotal: number;
    ratePerKm: number;
    owner: Principal;
    gstNumber?: string;
    createdDate: Time;
    distanceKm: number;
    totalAmount: number;
    paymentMode: PaymentMode;
    vehicle: string;
    partyName: string;
} {
    return {
        id: value.id,
        signature: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.signature)),
        calculatedTotal: value.calculatedTotal,
        ratePerKm: value.ratePerKm,
        owner: value.owner,
        gstNumber: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.gstNumber)),
        createdDate: value.createdDate,
        distanceKm: value.distanceKm,
        totalAmount: value.totalAmount,
        paymentMode: from_candid_PaymentMode_n19(uploadFile, downloadFile, value.paymentMode),
        vehicle: value.vehicle,
        partyName: value.partyName
    };
}
function from_candid_record_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: number;
    entries: Array<_ExpenseEntry>;
}): {
    total: number;
    entries: Array<ExpenseEntry>;
} {
    return {
        total: value.total,
        entries: from_candid_vec_n29(uploadFile, downloadFile, value.entries)
    };
}
function from_candid_record_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    paymentDescription: string;
    owner: Principal;
    date: _Time;
    description: string;
    paymentMode: _PaymentMode;
    category: _ExpenseCategory;
    amount: number;
}): {
    id: number;
    paymentDescription: string;
    owner: Principal;
    date: Time;
    description: string;
    paymentMode: PaymentMode;
    category: ExpenseCategory;
    amount: number;
} {
    return {
        id: value.id,
        paymentDescription: value.paymentDescription,
        owner: value.owner,
        date: value.date,
        description: value.description,
        paymentMode: from_candid_PaymentMode_n19(uploadFile, downloadFile, value.paymentMode),
        category: from_candid_ExpenseCategory_n32(uploadFile, downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: number;
    entries: Array<_IncomeEntry>;
}): {
    total: number;
    entries: Array<IncomeEntry>;
} {
    return {
        total: value.total,
        entries: from_candid_vec_n37(uploadFile, downloadFile, value.entries)
    };
}
function from_candid_record_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignee: string;
    toDestination: string;
    paymentDescription: string;
    owner: Principal;
    fromDestination: string;
    date: _Time;
    description: string;
    paymentMode: _PaymentMode;
    vehicle: string;
    bytes: number;
    amount: number;
    driver: string;
}): {
    assignee: string;
    toDestination: string;
    paymentDescription: string;
    owner: Principal;
    fromDestination: string;
    date: Time;
    description: string;
    paymentMode: PaymentMode;
    vehicle: string;
    bytes: number;
    amount: number;
    driver: string;
} {
    return {
        assignee: value.assignee,
        toDestination: value.toDestination,
        paymentDescription: value.paymentDescription,
        owner: value.owner,
        fromDestination: value.fromDestination,
        date: value.date,
        description: value.description,
        paymentMode: from_candid_PaymentMode_n19(uploadFile, downloadFile, value.paymentMode),
        vehicle: value.vehicle,
        bytes: value.bytes,
        amount: value.amount,
        driver: value.driver
    };
}
function from_candid_variant_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    financialYear: bigint;
} | {
    customRange: {
        endDate: _Time;
        startDate: _Time;
    };
} | {
    monthly: {
        month: bigint;
        year: bigint;
    };
} | {
    yearly: bigint;
} | {
    daily: {
        day: bigint;
        month: bigint;
        year: bigint;
    };
} | {
    weekly: {
        week: bigint;
        year: bigint;
    };
}): {
    __kind__: "financialYear";
    financialYear: bigint;
} | {
    __kind__: "customRange";
    customRange: {
        endDate: Time;
        startDate: Time;
    };
} | {
    __kind__: "monthly";
    monthly: {
        month: bigint;
        year: bigint;
    };
} | {
    __kind__: "yearly";
    yearly: bigint;
} | {
    __kind__: "daily";
    daily: {
        day: bigint;
        month: bigint;
        year: bigint;
    };
} | {
    __kind__: "weekly";
    weekly: {
        week: bigint;
        year: bigint;
    };
} {
    return "financialYear" in value ? {
        __kind__: "financialYear",
        financialYear: value.financialYear
    } : "customRange" in value ? {
        __kind__: "customRange",
        customRange: value.customRange
    } : "monthly" in value ? {
        __kind__: "monthly",
        monthly: value.monthly
    } : "yearly" in value ? {
        __kind__: "yearly",
        yearly: value.yearly
    } : "daily" in value ? {
        __kind__: "daily",
        daily: value.daily
    } : "weekly" in value ? {
        __kind__: "weekly",
        weekly: value.weekly
    } : value;
}
function from_candid_variant_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    balancePayment: null;
} | {
    bank: null;
} | {
    cash: null;
} | {
    cheque: null;
}): PaymentMode {
    return "upi" in value ? PaymentMode.upi : "balancePayment" in value ? PaymentMode.balancePayment : "bank" in value ? PaymentMode.bank : "cash" in value ? PaymentMode.cash : "cheque" in value ? PaymentMode.cheque : value;
}
function from_candid_variant_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dashboardError: {
        message: string;
    };
} | {
    dashboardQueryResult: {
        expenseTotals: {
            totalBank: number;
            totalCash: number;
            totalUpi: number;
            totalExpenses: number;
            totalCheque: number;
            totalBalancePayment: number;
        };
        incomeTotals: {
            totalIncome: number;
            totalBank: number;
            totalCash: number;
            totalUpi: number;
            totalCheque: number;
            totalBalancePayment: number;
        };
        dateRange: {
            endDate: _Time;
            startDate: _Time;
        };
    };
}): {
    __kind__: "dashboardError";
    dashboardError: {
        message: string;
    };
} | {
    __kind__: "dashboardQueryResult";
    dashboardQueryResult: {
        expenseTotals: {
            totalBank: number;
            totalCash: number;
            totalUpi: number;
            totalExpenses: number;
            totalCheque: number;
            totalBalancePayment: number;
        };
        incomeTotals: {
            totalIncome: number;
            totalBank: number;
            totalCash: number;
            totalUpi: number;
            totalCheque: number;
            totalBalancePayment: number;
        };
        dateRange: {
            endDate: Time;
            startDate: Time;
        };
    };
} {
    return "dashboardError" in value ? {
        __kind__: "dashboardError",
        dashboardError: value.dashboardError
    } : "dashboardQueryResult" in value ? {
        __kind__: "dashboardQueryResult",
        dashboardQueryResult: value.dashboardQueryResult
    } : value;
}
function from_candid_variant_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: any): ExpenseCategory {
    return "salary" in value ? ExpenseCategory.salary : "cngGas" in value ? ExpenseCategory.cngGas : "petrol" in value ? ExpenseCategory.petrol : "commissionVendor" in value ? ExpenseCategory.commissionVendor : "tollCharges" in value ? ExpenseCategory.tollCharges : "diesel" in value ? ExpenseCategory.diesel : "parkingCharges" in value ? ExpenseCategory.parkingCharges : "fraud" in value ? ExpenseCategory.fraud : "maintenanceAndRepair" in value ? ExpenseCategory.maintenanceAndRepair : "otherExpenses" in value ? ExpenseCategory.otherExpenses : "purchase" in value ? ExpenseCategory.purchase : value as ExpenseCategory;
}
function from_candid_vec_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BillEntry>): Array<BillEntry> {
    return value.map((x)=>from_candid_BillEntry_n16(uploadFile, downloadFile, x));
}
function from_candid_vec_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExpenseEntry>): Array<ExpenseEntry> {
    return value.map((x)=>from_candid_ExpenseEntry_n30(uploadFile, downloadFile, x));
}
function from_candid_vec_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncomeEntry>): Array<IncomeEntry> {
    return value.map((x)=>from_candid_IncomeEntry_n38(uploadFile, downloadFile, x));
}
async function from_candid_vec_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PdfReport>): Promise<Array<PdfReport>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PdfReport_n9(uploadFile, downloadFile, x)));
}
function to_candid_ExpenseCategory_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): _ExpenseCategory {
    return to_candid_variant_n5(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_PaymentMode_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n3(uploadFile, downloadFile, value);
}
function to_candid_ReportPeriod_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportPeriod): _ReportPeriod {
    return to_candid_variant_n42(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    upi: null;
} | {
    balancePayment: null;
} | {
    bank: null;
} | {
    cash: null;
} | {
    cheque: null;
} {
    return value == PaymentMode.upi ? {
        upi: null
    } : value == PaymentMode.balancePayment ? {
        balancePayment: null
    } : value == PaymentMode.bank ? {
        bank: null
    } : value == PaymentMode.cash ? {
        cash: null
    } : value == PaymentMode.cheque ? {
        cheque: null
    } : value;
}
function to_candid_variant_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_balance_other_bank_cash): {
    balance: null;
} | {
    other: null;
} | {
    bank: null;
} | {
    cash: null;
} {
    return value == Variant_balance_other_bank_cash.balance ? {
        balance: null
    } : value == Variant_balance_other_bank_cash.other ? {
        other: null
    } : value == Variant_balance_other_bank_cash.bank ? {
        bank: null
    } : value == Variant_balance_other_bank_cash.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "financialYear";
    financialYear: bigint;
} | {
    __kind__: "customRange";
    customRange: {
        endDate: Time;
        startDate: Time;
    };
} | {
    __kind__: "monthly";
    monthly: {
        month: bigint;
        year: bigint;
    };
} | {
    __kind__: "yearly";
    yearly: bigint;
} | {
    __kind__: "daily";
    daily: {
        day: bigint;
        month: bigint;
        year: bigint;
    };
} | {
    __kind__: "weekly";
    weekly: {
        week: bigint;
        year: bigint;
    };
}): {
    financialYear: bigint;
} | {
    customRange: {
        endDate: _Time;
        startDate: _Time;
    };
} | {
    monthly: {
        month: bigint;
        year: bigint;
    };
} | {
    yearly: bigint;
} | {
    daily: {
        day: bigint;
        month: bigint;
        year: bigint;
    };
} | {
    weekly: {
        week: bigint;
        year: bigint;
    };
} {
    return value.__kind__ === "financialYear" ? {
        financialYear: value.financialYear
    } : value.__kind__ === "customRange" ? {
        customRange: value.customRange
    } : value.__kind__ === "monthly" ? {
        monthly: value.monthly
    } : value.__kind__ === "yearly" ? {
        yearly: value.yearly
    } : value.__kind__ === "daily" ? {
        daily: value.daily
    } : value.__kind__ === "weekly" ? {
        weekly: value.weekly
    } : value;
}
function to_candid_variant_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): any {
    return value == ExpenseCategory.salary ? {
        salary: null
    } : value == ExpenseCategory.cngGas ? {
        cngGas: null
    } : value == ExpenseCategory.petrol ? {
        petrol: null
    } : value == ExpenseCategory.commissionVendor ? {
        commissionVendor: null
    } : value == ExpenseCategory.tollCharges ? {
        tollCharges: null
    } : value == ExpenseCategory.diesel ? {
        diesel: null
    } : value == ExpenseCategory.parkingCharges ? {
        parkingCharges: null
    } : value == ExpenseCategory.fraud ? {
        fraud: null
    } : value == ExpenseCategory.maintenanceAndRepair ? {
        maintenanceAndRepair: null
    } : value == ExpenseCategory.otherExpenses ? {
        otherExpenses: null
    } : value == ExpenseCategory.purchase ? {
        purchase: null
    } : value;
}
function to_candid_variant_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
